### PR TITLE
Flatpak of the app

### PR DESCRIPTION
**Pull request by yodatak**

### CODE REVIEW

**Comment by damonlynch** [comment]
Thank you for doing this work @yodatak! A couple of questions:

1. Does this build a working flatpak, such that the program can download photos/videos from cameras & mobile phones?
2. Does the vscode directory really need to be part of this pull request?

**Comment by yodatak** [comment]
hello the vscode is not need , 
for now i'm stuck un compiling udisk2 because it needed to inspection of disk in python but this binding don't exist in the existing flatpak runtime of kde so i dont know what to do for now you could comment the part of  "udisk2" and you will have a runtime error in the app

**Comment by yodatak** [comment]
The udisk part of gnome runtime 
https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/master/elements/core-deps/udisks2.bst
the kde runtime manifest
https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/e9e930fb38b6c470ff4b668d4862be4bb86d2330/org.kde.Sdk.json.in

not sure to understand where the problem is 
https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt5.15lts-23.08/org.kde.Sdk.json.in?ref_type=heads

free desktop runtime 
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/udisks.bst?ref_type=heads

**Comment by yodatak** [comment]
I just make it works @damonlynch  and its works for me ( i just have to test more because i use smb share)

**Comment by damonlynch** [comment]
Many thanks for your hard work @yodatak! It looks like you're making fine progress.

Regarding testing, just 4% of Rapid Photo Downloader users primarily download from a network share — 75% download from a memory card reader, 33% from a camera, and 22% from a phone. I got these figures from a survey I have been running for a year or two.

What that means is you need to include in your testing seeing how Rapid Photo Downloader responds to system events regarding device insertion and removal. Start Rapid Photo Downloader, and once it has completed its start-up, do the following, under both Gnome (or any other desktop that uses GVFS), and KDE (which does not use GVFS):

1. Plugging in a memory card reader (with memory card), and ensuring that Rapid Photo Downloader detects that it has been installed
2. Unmounting / ejecting a memory card reader (with memory card), and ensuring that Rapid Photo Downloader detects that it has been removed
3. Doing the same for a camera
4. And the same for a smart phone

Unless you have already configured the Flatpak to allow for responding to the system-wide events issued by GVFS, Udisks2, and libgphoto2, I guarantee that it will fail to detect device insertion or removal. A leading Gnome developer once told me that Flatpak can be configured to detect them — he said something along the lines of "you need to punch a hole through the security barrier" (or words to that effect).

**Comment by yodatak** [comment]
Hello i make the ios part compiled i will make a PR to flathub if you are intrested ( i hope i understood well how the app works)

**Comment by damonlynch** [comment]
Hi @yodatak what tests have you undertaken so far?

**Comment by yodatak** [comment]
I close this instead of this https://github.com/flathub/flathub/pull/5631
I made test with my android my a7III and a USB card reader @damonlynch
If you want to maintain the app on flathub say it in the PR !

**Pull request closed without merging**
